x-defaults:
  &defaults
  # Remove "build" section below and only use this "image" section 
  # to avoid building the image yourself:
  # image: glubsy/livestream_saver:latest
  build:
    context: ..
    dockerfile: docker/Containerfile
  image: livestream_saver:latest
  restart: always
  # to upgrade yt-dlp on every container start
  init: true
  volumes:
    - type: bind
      # This path is relative to this here file
      source: ../downloads
      target: /downloads
    - type: bind
      source: ${HOME}/.config/livestream_saver
      target: /root/.config/livestream_saver

services:
  # Each service defines monitoring of a Youtube channel
  # Here are some examples provided by default
  Panko:
    <<: *defaults
    command: monitor -s Panko
  Bijou:
    <<: *defaults
    command: monitor -s Bijou
  Fuwamoco:
    <<: *defaults
    command: monitor -s Fuwamoco
  Prune:
    <<: *defaults
    command: monitor -s Prune
  # A channel URL to monitor can also be provided as argument
  Saba:
    <<: *defaults
    command: monitor https://www.youtube.com/channel/UCxsZ6NCzjU_t4YSxQLBcM5A
